"""Constants for the Blauberg Freshpoint integration."""

DOMAIN = "freshpoint"
DEFAULT_NAME = "Blauberg Freshpoint"
DEFAULT_PASSWORD = "1111"
DEFAULT_PORT = 4000
DEFAULT_SCAN_INTERVAL_SECONDS = 20
DEFAULT_DISCOVERY_BROADCAST = "255.255.255.255"
DEFAULT_DEVICE_ID = "DEFAULT_DEVICEID"

CONF_CONTROLLER_ID = "controller_id"
CONF_BROADCAST_ADDRESS = "broadcast_address"
CONF_SOURCE_ADDRESS = "source_address"
CONF_DEVICES = "devices"

PARAM_POWER = 0x0001
PARAM_SPEED_MODE = 0x0002
PARAM_TIMER_MODE = 0x0007
PARAM_MANUAL_SPEED = 0x0044
PARAM_OUTDOOR_TEMPERATURE = 0x001F
PARAM_SUPPLY_TEMPERATURE = 0x0020
PARAM_EXTRACT_INLET_TEMPERATURE = 0x0021
PARAM_EXTRACT_OUTLET_TEMPERATURE = 0x0022
PARAM_HUMIDITY = 0x0025
PARAM_CO2 = 0x0027
PARAM_SUPPLY_RPM = 0x004A
PARAM_EXTRACT_RPM = 0x004B
PARAM_FILTER_COUNTDOWN = 0x0064
PARAM_FILTER_RESET = 0x0065
PARAM_HEATER_CONTROL = 0x0068
PARAM_MOTOR_RUNTIME = 0x007E
PARAM_HEATER_STATUS = 0x0081
PARAM_FAULT_WARNING = 0x0083
PARAM_FILTER_STATUS = 0x0088
PARAM_DIRECTION = 0x00B7
PARAM_RECOVERY_EFFICIENCY = 0x0129
PARAM_FROST_PROTECTION = 0x030B
PARAM_VOC = 0x0320
PARAM_DEVICE_ID = 0x007C
PARAM_DEVICE_TYPE = 0x00B9

READ_PARAMS = [
    PARAM_POWER,
    PARAM_SPEED_MODE,
    PARAM_TIMER_MODE,
    PARAM_MANUAL_SPEED,
    PARAM_OUTDOOR_TEMPERATURE,
    PARAM_SUPPLY_TEMPERATURE,
    PARAM_EXTRACT_INLET_TEMPERATURE,
    PARAM_EXTRACT_OUTLET_TEMPERATURE,
    PARAM_HUMIDITY,
    PARAM_CO2,
    PARAM_SUPPLY_RPM,
    PARAM_EXTRACT_RPM,
    PARAM_FILTER_COUNTDOWN,
    PARAM_HEATER_CONTROL,
    PARAM_MOTOR_RUNTIME,
    PARAM_HEATER_STATUS,
    PARAM_FAULT_WARNING,
    PARAM_FILTER_STATUS,
    PARAM_DIRECTION,
    PARAM_RECOVERY_EFFICIENCY,
    PARAM_FROST_PROTECTION,
    PARAM_VOC,
    PARAM_DEVICE_TYPE,
]
