"""Constants for the Blauberg Freshpoint integration."""

DOMAIN = "freshpoint"
DEFAULT_NAME = "Blauberg Freshpoint"
DEFAULT_PASSWORD = "1111"
DEFAULT_PORT = 4000
DEFAULT_SCAN_INTERVAL_SECONDS = 20
DEFAULT_DISCOVERY_BROADCAST = "255.255.255.255"
DEFAULT_DEVICE_ID = "DEFAULT_DEVICEID"

CONF_CONTROLLER_ID = "controller_id"
CONF_DEVICES = "devices"

PARAM_POWER = 0x0001
PARAM_SPEED_MODE = 0x0002
PARAM_MANUAL_SPEED = 0x0044
PARAM_HUMIDITY = 0x0025
PARAM_SUPPLY_RPM = 0x004A
PARAM_EXTRACT_RPM = 0x004B
PARAM_FILTER_STATUS = 0x0088
PARAM_DIRECTION = 0x00B7
PARAM_RECOVERY_EFFICIENCY = 0x0129
PARAM_DEVICE_ID = 0x007C
PARAM_DEVICE_TYPE = 0x00B9

READ_PARAMS = [
    PARAM_POWER,
    PARAM_SPEED_MODE,
    PARAM_MANUAL_SPEED,
    PARAM_HUMIDITY,
    PARAM_SUPPLY_RPM,
    PARAM_EXTRACT_RPM,
    PARAM_FILTER_STATUS,
    PARAM_DIRECTION,
    PARAM_RECOVERY_EFFICIENCY,
    PARAM_DEVICE_TYPE,
]
